import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import "@fortawesome/fontawesome-free/css/all.min.css";
import "../styles/tailwind.css";
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Intershight',
  description: 'Generated by create next app',
}

const App = dynamic<object>(
  () => import("../app/page"),
  { ssr: false },
);

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
